/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StampsRouteImport } from './routes/stamps'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RecommendationRouteImport } from './routes/recommendation'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StampsStampIdRouteImport } from './routes/stamps.$stampId'
import { Route as StampsStampIdBuyRouteImport } from './routes/stamps.$stampId.buy'

const StampsRoute = StampsRouteImport.update({
  id: '/stamps',
  path: '/stamps',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StampsStampIdRoute = StampsStampIdRouteImport.update({
  id: '/$stampId',
  path: '/$stampId',
  getParentRoute: () => StampsRoute,
} as any)
const StampsStampIdBuyRoute = StampsStampIdBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => StampsStampIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/recommendation': typeof RecommendationRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/stamps': typeof StampsRouteWithChildren
  '/stamps/$stampId': typeof StampsStampIdRouteWithChildren
  '/stamps/$stampId/buy': typeof StampsStampIdBuyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/recommendation': typeof RecommendationRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/stamps': typeof StampsRouteWithChildren
  '/stamps/$stampId': typeof StampsStampIdRouteWithChildren
  '/stamps/$stampId/buy': typeof StampsStampIdBuyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/recommendation': typeof RecommendationRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/stamps': typeof StampsRouteWithChildren
  '/stamps/$stampId': typeof StampsStampIdRouteWithChildren
  '/stamps/$stampId/buy': typeof StampsStampIdBuyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/marketplace'
    | '/recommendation'
    | '/sell'
    | '/settings'
    | '/stamps'
    | '/stamps/$stampId'
    | '/stamps/$stampId/buy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/marketplace'
    | '/recommendation'
    | '/sell'
    | '/settings'
    | '/stamps'
    | '/stamps/$stampId'
    | '/stamps/$stampId/buy'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/marketplace'
    | '/recommendation'
    | '/sell'
    | '/settings'
    | '/stamps'
    | '/stamps/$stampId'
    | '/stamps/$stampId/buy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MarketplaceRoute: typeof MarketplaceRoute
  RecommendationRoute: typeof RecommendationRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  StampsRoute: typeof StampsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stamps': {
      id: '/stamps'
      path: '/stamps'
      fullPath: '/stamps'
      preLoaderRoute: typeof StampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stamps/$stampId': {
      id: '/stamps/$stampId'
      path: '/$stampId'
      fullPath: '/stamps/$stampId'
      preLoaderRoute: typeof StampsStampIdRouteImport
      parentRoute: typeof StampsRoute
    }
    '/stamps/$stampId/buy': {
      id: '/stamps/$stampId/buy'
      path: '/buy'
      fullPath: '/stamps/$stampId/buy'
      preLoaderRoute: typeof StampsStampIdBuyRouteImport
      parentRoute: typeof StampsStampIdRoute
    }
  }
}

interface StampsStampIdRouteChildren {
  StampsStampIdBuyRoute: typeof StampsStampIdBuyRoute
}

const StampsStampIdRouteChildren: StampsStampIdRouteChildren = {
  StampsStampIdBuyRoute: StampsStampIdBuyRoute,
}

const StampsStampIdRouteWithChildren = StampsStampIdRoute._addFileChildren(
  StampsStampIdRouteChildren,
)

interface StampsRouteChildren {
  StampsStampIdRoute: typeof StampsStampIdRouteWithChildren
}

const StampsRouteChildren: StampsRouteChildren = {
  StampsStampIdRoute: StampsStampIdRouteWithChildren,
}

const StampsRouteWithChildren =
  StampsRoute._addFileChildren(StampsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MarketplaceRoute: MarketplaceRoute,
  RecommendationRoute: RecommendationRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  StampsRoute: StampsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
